# Generated by Django 2.2.9 on 2022-01-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('event_type', models.SmallIntegerField(choices=[(1, 'Checkout'), (2, 'Subscribe-init'), (3, 'Subscribe-success'), (4, 'Unsubscribe')], default=0)),
                ('triggered_browser', models.CharField(blank=True, max_length=50, verbose_name='Browser')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'created',
            },
        ),
    ]
