# Generated by Django 2.2.9 on 2022-01-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
    ]
