# Generated by Django 2.2.9 on 2022-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventservice', '0002_remove_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(1, 'Checkout'), (2, 'Subscribe-init'), (3, 'Subscribe-success'), (4, 'Unsubscribe')], default=0),
        ),
    ]
